feature: ['feature/*', 'feat/*']
bugfix: ['fix/*', 'bugfix/*', 'bug/*']
chore: ['chore/*', 'maintenance/*']
documentation: ['docs/*', 'doc/*']
enhancement: ['enhancement/*', 'improve/*', 'improvement/*']
refactor: ['refactor/*']
performance: ['perf/*', 'performance/*']
style: ['style/*']
test: ['test/*', 'testing/*']
ci: ['ci/*', 'integration/*']
security: ['security/*']
dependencies: ['deps/*', 'dependencies/*'] 