services:
  # Combined service (monolithic deployment)
  - type: web
    name: stock-sense
    env: node
    buildCommand: npm install && npm run build:all
    startCommand: node run.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_PORT
        value: 10001
      - key: STOCK_API_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL 
        value: ${RENDER_EXTERNAL_URL}/api
      - key: NEXT_PUBLIC_APP_ENV
        value: production 