services:
  # Combined service (monolithic deployment)
  - type: web
    name: stock-sense
    env: node
    plan: free # Explicitly set plan to free, though this is likely controlled in Render UI
    buildCommand: |
      npm install && \
      echo "Starting backend build..." && \
      cd backend && npm install && npm run build && cd .. && \
      echo "Backend build finished. Starting frontend build..." && \
      cd frontend && npm install && \
      echo "Attempting Next.js build with output standalone..." && \
      cross-env NODE_OPTIONS=--max_old_space_size=384 npm run build && \
      echo "Next.js build command finished. Verifying standalone output..." && \
      if [ ! -d ".next/standalone" ]; then \
        echo "ERROR: .next/standalone directory NOT found after frontend build!" && \
        exit 1; \
      fi && \
      echo ".next/standalone directory verified." && \
      cd .. && \
      echo "All builds finished."
    startCommand: node run.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_PORT
        value: 10001
      - key: STOCK_API_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL 
        value: ${RENDER_EXTERNAL_URL}/api
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: INDIAN_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

# Define a separate cron job service for scheduled tasks if needed
# crons:
#   - name: log-cleanup
#     schedule: "0 0 * * *" # Daily at midnight
#     command: "echo \"Log cleanup placeholder\"" 