services:
  # Combined service (monolithic deployment)
  - type: web
    name: stock-sense
    env: node
    plan: free # Explicitly set plan to free, though this is likely controlled in Render UI
    buildCommand: |
      npm install && \
      echo "Starting backend build..." && \
      npm run build:backend && \
      echo "Backend build finished."
    startCommand: node run.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: STOCK_API_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL 
        value: ${RENDER_EXTERNAL_URL}/api
      - key: NEXT_PUBLIC_APP_ENV
        value: production
      - key: INDIAN_API_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

# Define a separate cron job service for scheduled tasks if needed
# crons:
#   - name: log-cleanup
#     schedule: "0 0 * * *" # Daily at midnight
#     command: "echo \"Log cleanup placeholder\"" 