services:
  # Combined service (monolithic deployment)
  - type: web
    name: stock-sense
    env: node
    plan: free # Explicitly set plan to free, though this is likely controlled in Render UI
    buildCommand: |
      npm install
      echo "Starting backend build..."
      cd backend && npm install && npm run build && cd ..
      echo "Backend build finished. Starting frontend build..."
      # Attempting frontend build with lower memory for Free Tier
      # This is a long shot and may fail or result in a very slow build
      cd frontend && npm install && cross-env NODE_OPTIONS=--max_old_space_size=384 npm run build && cd ..
      echo "Frontend build finished."
    startCommand: node run.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_PORT
        value: 10001
      - key: STOCK_API_KEY
        sync: false
      - key: NEXT_PUBLIC_API_URL 
        value: ${RENDER_EXTERNAL_URL}/api
      - key: NEXT_PUBLIC_APP_ENV
        value: production 