name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      
      - name: Generate changelog
        id: changelog
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREVIOUS_TAG" ]; then
            echo "CHANGELOG=$(git log --pretty=format:"- %s" | head -n 20)" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=$(git log --pretty=format:"- %s" $PREVIOUS_TAG..HEAD)" >> $GITHUB_OUTPUT
          fi
      
      - name: Build backend
        working-directory: ./backend
        run: |
          npm ci
          npm run build
      
      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      
      - name: Create ZIP archives
        run: |
          mkdir -p dist
          cd backend && zip -r ../dist/backend-${{ steps.get_version.outputs.VERSION }}.zip dist package.json package-lock.json README.md
          cd ../frontend && zip -r ../dist/frontend-${{ steps.get_version.outputs.VERSION }}.zip .next public package.json package-lock.json README.md
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## Stock-Sense v${{ steps.get_version.outputs.VERSION }}
            
            ### Changes
            ${{ steps.changelog.outputs.CHANGELOG }}
            
            ### Installation
            1. Download the backend and frontend ZIP files
            2. Extract and follow setup instructions in ENVIRONMENT_SETUP.md
          files: |
            dist/backend-${{ steps.get_version.outputs.VERSION }}.zip
            dist/frontend-${{ steps.get_version.outputs.VERSION }}.zip 